config/routes.rb
TravelTripper::Application.routes.draw do
  devise_for :users do
    get '/users/sign_in' => 'devise/sessions#new'
  end

  resources :contents

  

  root :to =>'contents#index'
end

app/models/content.rb
class Content < ActiveRecord::Base
  # attr_accessor :color, :text, :font
  belongs_to :user
  validates_presence_of :color, :title, :font, :user_id
  before_create :restrict_user_from_creating_one_more_record

  def restrict_user_from_creating_one_more_record
    errors.add(:base, "Cannot create one more record, instead update") if self.id.present? 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper ApplicationHelper
  
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  helper ApplicationHelper
  skip_before_filter :verify_authenticity_token
  
  def index
  end
  
  def new
    @content = Content.new
  end

  def create
    @content = Content.create(safe_params)
    if @content.save
      redirect_to root_path, notice: "Successfully created"
    else
      render :action => "new"
    end
  end

  def edit
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])
    @content.update_attributes!(safe_params)
    redirect_to root_path, notice: "Successfully Updated"
  end

  private
  def safe_params
    params.require(:content).permit(:color, :font, :title, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def customized_color
    color = current_user.content.color? ? "#cccccc" : current_user.content.color 
    return color
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
  def get_updated_color
    if current_user.content.present?
      current_user.content.color
    else
      "#B2CC54"
    end
  end
end

app/views/contents/_form.html.erb
<%= form_for @content, html: {:id => "content_form", class: 'form-horizontal'} do |f| %>
  <% @content.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
  <%= f.label :title, 'Enter Title' %>
  <%= f.text_field :title, required: true %></br></br>
  <%= f.label :color %>
  <%= f.text_field :color, :class => "jscolor", value: "#{get_updated_color}", required: true %></br></br>
  <%= f.label :font %>
  <%= f.text_field :font, id: "font", required: true %></br></br>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit %>
<% end %>

app/views/contents/edit.html.erb
<script type='text/javascript' >
  $(document).on('ready page:load', function(){
    $(function(){
      $('#font').fontselect().change(function(){
        // replace + signs with spaces for css
        var font = $(this).val().replace(/\+/g, ' ');
        // split font into family and weight
        font = font.split(':');
        // set family on paragraphs
        $('label,input,p').css('font-family', font[0]);
      });
    });
    var fontVal = $('.font-select a span').text();
    $('label,input,p').css('font-family', fontVal);
  });
</script>
<p>Title: <%= current_user.content.title %><p>
<% if @content.errors.any? %>
  <%= @content.errors.full_messages %>
<% else %>
  <%= render :partial => "form" %>
<% end %>

app/views/contents/index.html.erb
<div>
  <% if user_signed_in? %>
    <div id="main">
      <h2>You have succesfully signed in.</h2>
        <h4> Please click on Change Content link to impact styling to that page</h4>
          <% if current_user.content.blank? %>
            <%= link_to "Change Content", new_content_path, id: 'change_content','data-no-turbolink' =>'true' %>
          <% else %>
            <%= link_to "Edit Content", edit_content_path(:id => current_user.content.id), id: 'change_content','data-no-turbolink' =>'true' %>
          <% end %>
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    </div>
  <% else %>
    <h1> Welcome to Change Style</h1>
    <%= link_to "Sign In", new_user_session_path, :method => :get %>
    <%= link_to "Sign up", new_user_registration_path, :method => :get %>
  <% end %>              
</div>

app/views/contents/new.html.erb
<script type='text/javascript' >
  $(document).on('ready page:load', function(){
    $(function(){
      $('#font').fontselect().change(function(){
        // replace + signs with spaces for css
        var font = $(this).val().replace(/\+/g, ' ');
        // split font into family and weight
        font = font.split(':');
        // set family on paragraphs

        $('label,input,p').css('font-family', font[0]);
      });
    });
    var fontVal = $('.font-select a span').text();
    $('label,input,p').css('font-family', fontVal);
  });
</script>
<% if @content.errors.any? %>
  <%#= @content.errors.full_messages %>
<% end %>
<%= render :partial => "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelTripper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>